# Generated by Django 5.0.7 on 2024-08-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0004_subscriptions_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='permission',
            field=models.ManyToManyField(limit_choices_to={'codename__in': ['advanced', 'pro', 'basic', 'basic_ai'], 'content_type__app_label': 'subscriptions'}, to='auth.permission'),
        ),
    ]
