# Generated by Django 5.0.7 on 2024-08-18 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_subscriptions_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptions',
            old_name='permission',
            new_name='permissions',
        ),
    ]
